apiVersion: v1
kind: Service
metadata:
  name: crossbridge-svc
  namespace: crossbridge-prod
spec:
  type: LoadBalancer
  selector:
    app: crossbridge-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
